[build]
  command = "prisma generate && next build"
  publish = ".next"

[functions]
  included_files = ["prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "false"
  DATABASE_URL = "file:./prisma/dev.db"
